Task/Models/Staff.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Models
{
    public class Staff_Filter 
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Recorder { get; set; }
        public System.DateTime RecordDate { get; set; }
        public string UserLogin { get; set; }
        public string PasswordLogin { get; set; }
        public int StaffLevel { get; set; }
        public int Status { get; set; }
        public string Email { get; set; }
    }
    public class StaffLV
    {
        public int ID { get; set; }
        public string Name { get; set; }
    }
    public class EditStaffm
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Recorder { get; set; }
        public System.DateTime RecordDate { get; set; }
        public string UserLogin { get; set; }
        public string PasswordLogin { get; set; }
        public int StaffLevel { get; set; }
        public int Status { get; set; }
    }
}

Task/Controllers/StaffController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using RestSharp;
using Models;
using System.Web.Script.Serialization;
using System.Net;
using System.Reflection;
using PagedList;

namespace Task.Controllers
{
    public class StaffController : Controller
    {
        JobsEntities db = new JobsEntities();
        private int pageSize = 10;
        //
        public ActionResult Index()
        {
            int StaffLevel = HttpContext.Session["StaffLevel"] == null ? 0 : (int)HttpContext.Session["StaffLevel"];
            ViewBag.StaffLevel = StaffLevel;
            return View();
        }

        public ActionResult List(Models.Staff_Filter Filter, int pageNO = 1, int? RecorderID = null)
        {
            int StaffLevel = HttpContext.Session["StaffLevel"] == null ? 0 : (int)HttpContext.Session["StaffLevel"];
            ViewBag.StaffLevel = StaffLevel;

            string IDStaff = "";
            int IDStaff_num = 0;
            if (HttpContext.Session["LoginID"] != null)
            {
                IDStaff = HttpContext.Session["IDStaff"].ToString();

                IDStaff_num = int.Parse(IDStaff);
                ViewBag.IDStaff = IDStaff_num;
            }
            else
            {
                return RedirectToAction("LogIn", "Home");
            }

            try
            {
                var Item = db.masStaffs.Where(w => w.Status > 0).AsQueryable();
                if (StaffLevel != 1)
                {
                    Item = Item.Where(s => s.ID == IDStaff_num);
                }
                if (Filter.ID > 0 || !string.IsNullOrWhiteSpace(Filter.Name))
                {
                    if (Filter.ID > 0)
                    {
                        Item = Item.Where(w => w.ID == Filter.ID).AsQueryable();
                    }
                    if (!string.IsNullOrWhiteSpace(Filter.Name))
                    {
                        Item = Item.Where(w => w.Name.Contains(Filter.Name)).AsQueryable();
                    }
                }
                int.TryParse(Properties.Settings.Default.pageSize.ToString(), out pageSize);
                if (pageSize <= 0) { pageSize = 10; }
                int pageIdx = pageNO - 1;
                int totalItemCount = Item.Count();
                var paged = Item.OrderBy(o => o.Name).Skip(pageIdx * pageSize).Take(pageSize);
                var pageresult = new StaticPagedList<masStaffs>(paged, pageNO, pageSize, totalItemCount);
                ViewBag.RecorderID = RecorderID;

                return PartialView(pageresult);
            }
            catch (Exception ex)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, ex.ToString());
            }
        }
        public ActionResult Create()
        {
            int StaffLevel = HttpContext.Session["StaffLevel"] == null ? 0 : (int)HttpContext.Session["StaffLevel"];
            Staff_Filter Item = new Staff_Filter();

            List<StaffLV> StaffLV = new List<StaffLV>();
            StaffLV.Add(new StaffLV { ID = 1, Name = "Admin" });
            StaffLV.Add(new StaffLV { ID = 2, Name = "RD" });
            StaffLV.Add(new StaffLV { ID = 3, Name = "TS" });

            ViewBag.StaffLV = new SelectList(StaffLV,"ID","Name");
            return PartialView(Item);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Models.Staff_Filter Item)
        {
            int StaffLevel = HttpContext.Session["StaffLevel"] == null ? 0 : (int)HttpContext.Session["StaffLevel"];
            string ErrorMSG = ValidForNew(Item,true); //ฟังชั่นเช็คค่าว่างกับตัวอักษร true กับ false
            if (!ErrorMSG.Equals(string.Empty))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, ErrorMSG);
            }
            if (Item != null)
            {
                var getid = db.masStaffs;
                masStaffs data = new masStaffs()
                {
                    Name = Item.Name,
                    Recorder = StaffLevel.ToString(),
                    RecordDate = DateTime.Now,
                    UserLogin = Item.UserLogin,
                    PasswordLogin = Item.PasswordLogin,
                    StaffLevel = Item.StaffLevel,
                    Email = Item.Email,
                    Status = 1,
                };
                db.masStaffs.Add(data);
                try
                {
                    db.SaveChanges();
                }
                catch (Exception ex)
                {

                }
            }

            return new HttpStatusCodeResult(HttpStatusCode.OK);

        }

        public ActionResult Edit(int ID,int LV)
        {
            int StaffLevel = HttpContext.Session["StaffLevel"] == null ? 0 : (int)HttpContext.Session["StaffLevel"];
            Models.Staff_Filter Item = new Staff_Filter();
            List<StaffLV> StaffLV = new List<StaffLV>();
            StaffLV.Add(new StaffLV { ID = 1, Name = "Admin" });
            StaffLV.Add(new StaffLV { ID = 2, Name = "RD" });
            StaffLV.Add(new StaffLV { ID = 3, Name = "TS" });
            var getmassStaff = db.masStaffs.FirstOrDefault(s => s.ID == ID);


            if (getmassStaff != null)
            {
                Item.ID = getmassStaff.ID;
                Item.Name = getmassStaff.Name;
                Item.UserLogin = getmassStaff.UserLogin;
                Item.PasswordLogin = getmassStaff.PasswordLogin;
                Item.StaffLevel = getmassStaff.StaffLevel;
                ViewBag.LV = LV;
                ViewBag.LV_Staff = getmassStaff.StaffLevel;
                ViewBag.StaffLVs = new SelectList(StaffLV, "ID", "Name");
                Item.Email = getmassStaff.Email;
            }
            
            return PartialView(Item);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Models.Staff_Filter Item)
        {
            int StaffLevel = HttpContext.Session["StaffLevel"] == null ? 0 : (int)HttpContext.Session["StaffLevel"];
            string ErrorMSG = ValidForNew(Item,false); //ฟังชั่นเช็คค่าว่างกับตัวอักษร true กับ false
            if (!ErrorMSG.Equals(string.Empty))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, ErrorMSG);
            }
            if (Item != null)
            {
                var getidmassStaff = db.masStaffs.FirstOrDefault(s => s.ID == Item.ID);
                if (getidmassStaff != null)
                {
                    getidmassStaff.Name = Item.Name;
                    getidmassStaff.Recorder = StaffLevel.ToString();
                    getidmassStaff.RecordDate = DateTime.Now;
                    getidmassStaff.UserLogin = Item.UserLogin;
                    getidmassStaff.PasswordLogin = Item.PasswordLogin;
                    getidmassStaff.StaffLevel = Item.StaffLevel;
                    getidmassStaff.Status = 1;
                    getidmassStaff.Email = Item.Email;
                }
                try
                {
                    db.SaveChanges();
                }
                catch (Exception ex)
                {

                }
            }

            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }
        public ActionResult Delete(int ID)
        {
            int StaffLevel = HttpContext.Session["StaffLevel"] == null ? 0 : (int)HttpContext.Session["StaffLevel"];
            var Item = db.masStaffs.Find(ID);
            return PartialView(Item);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Models.Staff_Filter Item)
        {
            int StaffLevel = HttpContext.Session["StaffLevel"] == null ? 0 : (int)HttpContext.Session["StaffLevel"];

            if (Item != null)
            {
                var getidmassStaff = db.masStaffs.FirstOrDefault(s => s.ID == Item.ID);
                if (getidmassStaff != null)
                {
                    getidmassStaff.Recorder = StaffLevel.ToString();
                    getidmassStaff.RecordDate = DateTime.Now;
                    getidmassStaff.Status = 0;
                }
                try
                {
                    db.SaveChanges();
                }
                catch (Exception ex)
                {

                }
            }

            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }
        public string ValidForNew(Models.Staff_Filter Item,bool create =true) //create=true ให้เช็คค่าเลยกำหนดใน create กับ Edit ที่สร้างมา
        {
            int StaffLevel = HttpContext.Session["StaffLevel"] == null ? 0 : (int)HttpContext.Session["StaffLevel"];
            string resume = string.Empty;
            string ErrorAlert = string.Empty;
            string ErrorRow = string.Empty;
            //int n;
            
            if (Item != null)
            {
                if (create)
                {
                    if (Item.Name == null)
                    {
                        resume += "AA,";
                    }
                    else if (Item.Name.Count() >= 255)
                    {
                        resume += "AB,";
                    }
                    if (Item.UserLogin == null)
                    {
                        resume += "BA,";
                    }
                    else if (Item.UserLogin.Count() >= 50)
                    {
                        resume += "BB,";
                    }
                    if (Item.PasswordLogin == null)
                    {
                        resume += "CA,";
                    }
                    else if (Item.PasswordLogin.Count() >= 50)
                    {
                        resume += "CB,";
                    }
                    if (String.IsNullOrWhiteSpace(Item.Email))
                    {

Task/Views/Staff/Create.cshtml
@model  Models.Staff_Filter

@using (Html.BeginForm("Create", "Staff", FormMethod.Post, new { id = "form0", enctype = "multipart/form-data" }))
{
    <div class="modal-dialog modal-lg" style="width: 800px; left: -150px">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">@Resources.Resource.Create</h4>
            </div>
            <div class="modal-body" style="width: 600px;">
                @Html.AntiForgeryToken()
                <div class="form-horizontal">
                    @Html.ValidationSummary(true)
                    <div class="form-group">
                        @Html.Label("Name", new { @class = "control-label col-md-5" })
                        <div class="col-md-7">
                            @Html.EditorFor(model => model.Name, new { @class = "control-label col-md-5", Styles = "width:100%" })
                            <span id="AError" class="ValidDateError"></span>
                        </div>
                    </div>

                    @*--------Piyapan--------*@
                    <div class="form-group">
                        @Html.Label("Status", new { @class = "control-label col-md-5" })
                        
                        <div class="col-md-7">
                            @Html.DropDownList("StaffLevel", (IEnumerable<SelectListItem>)ViewBag.StaffLV, new { @class = "control-label col-md-5" })
                            @*@Html.EditorFor(model => model.StaffLevel, new { @class = "control-label col-md-5", Styles = "width:100%" })*@
                            <span id="AError" class="ValidDateError"></span>
                        </div>
                    </div>
                    @*--------Piyapan--------*@

                    <div class="form-group">
                        @Html.Label("UserLogin", new { @class = "control-label col-md-5" })
                        <div class="col-md-7">
                            @Html.EditorFor(model => model.UserLogin, new { @class = "control-label col-md-5", Styles = "width:100%" })
                            <span id="BError" class="ValidDateError"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.Label("PasswordLogin", new { @class = "control-label col-md-5" })
                        <div class="col-md-7">
                            @Html.EditorFor(model => model.PasswordLogin, new { @class = "control-label col-md-5", Styles = "width:100%" })
                            <span id="CError" class="ValidDateError"></span>
                        </div>
                    </div>

                    @*---------mos------------*@
                    <div class="form-group">
                        @Html.Label("Email", new { @class = "control-label col-md-5" })
                        <div class="col-md-7">
                            @Html.EditorFor(model => model.Email, new { @class = "control-label col-md-5", Styles = "width:100%" })
                            <span id="DError" class="ValidDateError"></span>
                        </div>
                    </div>

                </div>
            </div>
            <div class="modal-footer">
                <input type="button" class="btn" onclick="hideDialog();" value="@Resources.Resource.Close">
                <input type="submit" value="@Resources.Resource.Save" class="btn btn-primary btn-md" />
            </div>
        </div>
        
    </div>}
@{ Html.RenderPartial("../Loading"); }



                }
<script src="~/Scripts/CHO.js"></script>
<script lang="javascript">
    $(document).ready(function () {
        $(function () {
            var SubURL = '';
            $("#DueDate").datepicker({
                dateFormat: "dd/M/yy",
                changeMonth: true,
                changeYear: true,
                showButtonPanel: true,
                buttonImage: SubURL + "/images/calendar.gif",
                showOn: "both"
            });

        });



    });
</script>
<script type="text/javascript">


    $(function () {
        $("#form0").submit(function (event) {
            $("#inloading").show();
            var dataString;
            event.preventDefault();
            var action = $("#form0").attr("action");
            if ($("#form0").attr("enctype") == "multipart/form-data") {
                dataString = new FormData($("#form0").get(0));
                contentType = false;
                processData = false;
            } else {
                // regular form, do your own thing if you need it
            }
            $.ajax({
                type: "POST",
                url: action,
                data: dataString,
                //dataType: "json", //change to your own, else read my note above on enabling the JsonValueProviderFactory in MVC
                contentType: contentType,
                processData: processData,
                success: function (data) {
                    //BTW, data is one of the worst names you can make for a variable
                    //handleSuccessFunctionHERE(data);

                    alert("Add Data Success");
                    created();
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    $("#inloading").hide();
                    //$("#ErPosNo").html("test")
                    //alert(errorThrown);
                    errorClear();
                    Error(errorThrown);

                }
            });
        }); //end .submit()
    });

</script>

Task/Views/Staff/Delete.cshtml
@model masStaffs

@using (Html.BeginForm("Delete", "Staff", FormMethod.Post, new { id = "form0", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="modal-dialog modal-lg" style="width:800px;left:-150px">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">@Resources.Resource.Delete</h4>
                <center><h4>@Html.Label("คุณต้องการลบ masStaff นี้ใช่หรือไม่")</h4></center>
            </div>
            <div class="modal-body" style="width:800px;">
                <div class="form-horizontal">
                    @Html.ValidationSummary(true)
                    @Html.HiddenFor(model => model.ID)
                    <div class="form-group">
                        @Html.Label("masStaff ID", new { @class = "control-label col-md-5" })
                        <div class="col-md-7">
                            @Html.DisplayFor(model => model.ID, new { @class = "control-label col-md-5", Styles = "width:100%" })
                            <span id="AError" class="ValidDateError"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.Label("Name", new { @class = "control-label col-md-5" })
                        <div class="col-md-7">
                            @Html.DisplayFor(model => model.Name, new { @class = "control-label col-md-5", Styles = "width:100%" })
                            <span id="CError" class="ValidDateError"></span>
                        </div>
                    </div>
                </div>
            </div>
            @{ Html.RenderPartial("../Loading"); }
            <div class="modal-footer">
                <input type="button" class="btn" onclick="hideDialog();" value="No">
                <input type="submit" value="Yes" class="btn btn-primary btn-md" />
            </div>
        </div>
    </div>
                }
<script src="~/Scripts/CHO.js"></script>
<script lang="javascript">
    $(document).ready(function () {
        $(function () {
            var SubURL = '';
            $("#DueDate").datepicker({
                dateFormat: "dd/M/yy",
                changeMonth: true,
                changeYear: true,
                showButtonPanel: true,
                buttonImage: SubURL + "/images/calendar.gif",
                showOn: "both"
            });

        });



    });
</script>
<script type="text/javascript">
    $(function () {
        $("#form0").submit(function (event) {
            $("#inloading").show(); var dataString;
            event.preventDefault();
            var action = $("#form0").attr("action");
            if ($("#form0").attr("enctype") == "multipart/form-data") {
                dataString = new FormData($("#form0").get(0));
                contentType = false;
                processData = false;
            } else {
                // regular form, do your own thing if you need it
            }
            $.ajax({
                type: "POST",
                url: action,
                data: dataString,
                //dataType: "json", //change to your own, else read my note above on enabling the JsonValueProviderFactory in MVC
                contentType: contentType,
                processData: processData,
                success: function (data) {
                    //BTW, data is one of the worst names you can make for a variable
                    //handleSuccessFunctionHERE(data);
                    $("#inloading").hide();
                    alert("Delete Data Success");
                    created();
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    $("#inloading").hide();
                    //$("#ErPosNo").html("test")
                    errorClear();
                    Error(errorThrown);

                }
            });
        }); //end .submit()
    });
</script>

Task/Views/Staff/Edit.cshtml
@model Models.Staff_Filter

@using (Html.BeginForm("Edit", "Staff", FormMethod.Post, new { id = "form0", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="modal-dialog modal-lg" style="width:800px;left:-150px">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">@Resources.Resource.Edit</h4>
            </div>
            <div class="modal-body" style="width:800px;">
                <div class="form-horizontal">
                    @Html.ValidationSummary(true)
                    @Html.HiddenFor(model => model.ID)
                    <div class="form-group">
                        @Html.Label("masStaff ID", new { @class = "control-label col-md-5" })
                        <div class="col-md-7">
                            @Html.DisplayFor(model => model.ID, new { @class = "control-label col-md-5", Styles = "width:100%" })
                            <span id="Error" class="ValidDateError"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.Label("Name", new { @class = "control-label col-md-5" })
                        <div class="col-md-7">
                            @Html.EditorFor(model => model.Name, new { @class = "control-label col-md-5", Styles = "width:100%" })
                            <span id="AError" class="ValidDateError"></span>
                        </div>
                    </div>


                    @*--------Piyapan--------*@

                    @if (ViewBag.LV == 1)
                    {
                        <div class="form-group">

                            @Html.Label("Status", new { @class = "control-label col-md-5" })

                            <div class="col-md-7">
                                @Html.DropDownListFor(model => model.StaffLevel, (IEnumerable<SelectListItem>)ViewBag.StaffLVs, new { @class = "control-label col-md-5" })
                                <span id="AError" class="ValidDateError"></span>
                            </div>
                        </div>
                    }
                    else
                    {
                        <div class="form-group">

                            @Html.Label("Status", new { @class = "control-label col-md-5" })

                            <div class="col-md-7">
                                @if(ViewBag.LV_Staff == 1)
                                {
                                    <p>Admin</p>
                                }
                                else
                                {
                                    <p>Staff</p>
                                }
                                <span id="AError" class="ValidDateError"></span>
                            </div>
                        </div>
                    }
                    @*--------Piyapan--------*@


                    <div class="form-group">
                        @Html.Label("UserLogin", new { @class = "control-label col-md-5" })
                        <div class="col-md-7">
                            @Html.EditorFor(model => model.UserLogin, new { @class = "control-label col-md-5", Styles = "width:100%" })
                            <span id="BError" class="ValidDateError"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.Label("PasswordLogin", new { @class = "control-label col-md-5" })
                        <div class="col-md-7">
                            @Html.EditorFor(model => model.PasswordLogin, new { @class = "control-label col-md-5", Styles = "width:100%" })
                            <span id="CError" class="ValidDateError"></span>
                        </div>
                    </div>

                    @*----------mos---------------*@
                    @*<div class="form-group">
                        @Html.Label("Email", new { @class = "control-label col-md-5" })
                        <div class="col-md-7">
                            @Html.EditorFor(model => model.UserEmail, new { @class = "control-label col-md-5", Styles = "width:100%" })
                            <span id="CError" class="ValidDateError"></span>
                        </div>
                    </div>*@
                    <div class="form-group">
                        @Html.Label("Email", new { @class = "control-label col-md-5" })
                        <div class="col-md-7">
                            @Html.EditorFor(model => model.Email, new { @class = "control-label col-md-5", Styles = "width:100%" })
                            <span id="AError" class="ValidDateError"></span>
                        </div>
                    </div>

                </div>
            </div>
            @{ Html.RenderPartial("../Loading"); }
            <div class="modal-footer">
                <input type="button" class="btn" onclick="hideDialog();" value="@Resources.Resource.Close">
                <input type="submit" value="@Resources.Resource.Save" class="btn btn-primary btn-md" />
            </div>
        </div>
    </div>
                }
<script src="~/Scripts/CHO.js"></script>
<script lang="javascript">
    $(document).ready(function () {
        $(function () {
            var SubURL = '';
            $("#DueDate").datepicker({
                dateFormat: "dd/M/yy",
                changeMonth: true,
                changeYear: true,
                showButtonPanel: true,
                buttonImage: SubURL + "/images/calendar.gif",
                showOn: "both"
            });

        });



    });
</script>
<script type="text/javascript">
    $(function () {
        $("#form0").submit(function (event) {
            $("#inloading").show(); var dataString;
            event.preventDefault();
            var action = $("#form0").attr("action");
            if ($("#form0").attr("enctype") == "multipart/form-data") {
                dataString = new FormData($("#form0").get(0));
                contentType = false;
                processData = false;
            } else {
                // regular form, do your own thing if you need it
            }
            $.ajax({
                type: "POST",
                url: action,
                data: dataString,
                //dataType: "json", //change to your own, else read my note above on enabling the JsonValueProviderFactory in MVC
                contentType: contentType,
                processData: processData,
                success: function (data) {
                    //BTW, data is one of the worst names you can make for a variable
                    //handleSuccessFunctionHERE(data);
                    $("#inloading").hide();
                    alert("Edit Data Success");
                    created();
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    $("#inloading").hide();
                    //$("#ErPosNo").html("test")
                    errorClear();
                    Error(errorThrown);

                }
            });
        }); //end .submit()
    });
</script>

Task/Views/Staff/List.cshtml
@model PagedList.IPagedList<masStaffs>
<table class="table">
    <thead>
        <tr style="background-color: #428bca; color:white">
            <th class="Name">
                @Html.Label("ID")
            </th>
            <th class="Name">
                @Html.Label("Name")
            </th>
            <th class="Name">
                @Html.Label("Status")
            </th>
            <th style="text-align:right;padding-right:1.5em" colspan="3"><span class="badge">@Model.TotalItemCount</span>  @Resources.Resource.Records</th>
        </tr>
    </thead>
    <tbody>

        

        @foreach (masStaffs Item in Model)
        {
            
            <tr>
                <td class="Name">
                    @Html.HiddenFor(model => Item.ID)
                    @Html.DisplayFor(modelItem => Item.ID)
                </td>
                <td class="Name">
                    @Html.DisplayFor(modelItem => Item.Name)
                </td>
                <td class="Name">
                    @if (Item.StaffLevel == 1)
                    {
                        <p>Admin</p>
                    }
                    else if(Item.StaffLevel == 2)
                    {
                        <p>RD</p>
                    }
                    else
                    {
                        <p>TS</p>
                    }
                </td>

                <td style="text-align:right;">
                    @if (Item.StaffLevel >= 1)
                    {
                        @Html.ActionLink(@Resources.Resource.Edit, "Edit", "Staff", new { ID = Item.ID,LV = ViewBag.StaffLevel },
                          new
                          {
                              @class = "btn btn-primary btn-md",
                              data_toggle = "modal",
                              data_target = "#detailsDialog",
                              role = "button"
                          })
                    }
                    @if (Item.StaffLevel >= 1)
                    {
                        @Html.ActionLink(@Resources.Resource.Delete, "Delete", "Staff", new { ID = Item.ID },
                    new
                    {
                        @class = "btn btn-primary btn-md",
                        data_toggle = "modal",
                        data_target = "#detailsDialog",
                        role = "button"
                    })
                    }
                </td>
            </tr>
            
        }
    </tbody>
</table>
<div class="panel-footer">
    @Html.PagedListPager(Model, page => "javascript:pageTo(" + page + ");")
</div>
@*<style>
        .button
        {
            position:absolute;
            top:50%;
        }
    </style>*@