Task/Models/Project.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Models
{
    public class Project_Filter 
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Recorder { get; set; }
        public System.DateTime RecordDate { get; set; }
        public int Status { get; set; }
    }
}

Task/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using RestSharp;
using Models;
using System.Web.Script.Serialization;
using System.Net;
using System.Reflection;
using PagedList;

namespace Task.Controllers
{
    public class ProjectController : Controller
    {
        JobsEntities db = new JobsEntities();
        private int pageSize = 10;
        //
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult List(Models.Project_Filter Filter, int pageNO = 1, int? RecorderID = null)
        {
            int StaffLevel = HttpContext.Session["StaffLevel"] == null ? 0 : (int)HttpContext.Session["StaffLevel"];
            try
            {
                var Item = db.masProjects.Where(w => w.Status > 0).AsQueryable();
                if (Filter != null)
                {
                    if (Filter.ID > 0)
                    {
                        Item = Item.Where(w => w.ID == Filter.ID).AsQueryable();
                    }
                    if (!string.IsNullOrWhiteSpace(Filter.Name))
                    {
                        Item = Item.Where(w => w.Name.Contains(Filter.Name)).AsQueryable();
                    }
                }
                int.TryParse(Properties.Settings.Default.pageSize.ToString(), out pageSize);
                if (pageSize <= 0) { pageSize = 10; }
                int pageIdx = pageNO - 1;
                int totalItemCount = Item.Count();
                var paged = Item.OrderBy(o => o.Name).Skip(pageIdx * pageSize).Take(pageSize);
                var pageresult = new StaticPagedList<masProjects>(paged, pageNO, pageSize, totalItemCount);
                ViewBag.RecorderID = RecorderID;
                return PartialView(pageresult);
            }
            catch (Exception ex)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, ex.ToString());
            }
        }
        //private Models.Project_Filter EntityToModel(tranTask Value)
        //{
        //    return new Models.Project_Filter()
        //    {
        //        ID = Value.ID,
        //        Name = Value.Name,
        //        DueDate = Value.DueDate,
        //        ProjectID = Value.ProjectID,
        //        ProjectName= Value.masProject.Name,
        //        Remark = Value.Remark,
        //        StaffID = Value.StaffID,
        //        StaffName = Value.masStaff==null? "":Value.masStaff.Name,
        //        StartDate = Value.StartDate,
        //        StatusID = Value.StatusID,
        //        StatusName = Value.masTaskStatu.Name
        //    };
        //}
        public ActionResult Create()
        {
            int StaffLevel = HttpContext.Session["StaffLevel"] == null ? 0 : (int)HttpContext.Session["StaffLevel"];
            Project_Filter Item = new Project_Filter();
            return PartialView(Item);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Models.Project_Filter Item)
        {
            int StaffLevel = HttpContext.Session["StaffLevel"] == null ? 0 : (int)HttpContext.Session["StaffLevel"];
            string ErrorMSG = ValidForNew(Item, true); //ฟังชั่นเช็คค่าว่างกับตัวอักษร true กับ false
            if (!ErrorMSG.Equals(string.Empty))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, ErrorMSG);
            }
            if (Item != null)
            {
                var getid = db.masProjects;
                masProjects data = new masProjects()
                {

                    Name = Item.Name,
                    Recorder = StaffLevel.ToString(),
                    RecordDate = DateTime.Now,
                    Status = 1,
                };
                db.masProjects.Add(data);
                try
                {
                    db.SaveChanges();
                }
                catch (Exception ex)
                {

                }
            }

            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }

        public ActionResult Edit(int ID)
        {
            int StaffLevel = HttpContext.Session["StaffLevel"] == null ? 0 : (int)HttpContext.Session["StaffLevel"];
            Models.Project_Filter Item = new Project_Filter();
            var getmassProjects = db.masProjects.FirstOrDefault(s => s.ID == ID);
            if (getmassProjects != null)
            {
                Item.ID = getmassProjects.ID;
                Item.Name = getmassProjects.Name;
                Item.Recorder = StaffLevel.ToString();
                Item.RecordDate = DateTime.Now;
                Item.Status = 1;
            }

            return PartialView(Item);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Models.Project_Filter Item)
        {
            int StaffLevel = HttpContext.Session["StaffLevel"] == null ? 0 : (int)HttpContext.Session["StaffLevel"];
            string ErrorMSG = ValidForNew(Item, true); //ฟังชั่นเช็คค่าว่างกับตัวอักษร true กับ false
            if (!ErrorMSG.Equals(string.Empty))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, ErrorMSG);
            }
            if (Item != null)
            {
                var getidmasProjects = db.masProjects.FirstOrDefault(s => s.ID == Item.ID);
                if (getidmasProjects != null)
                {
                    getidmasProjects.Name = Item.Name;
                    getidmasProjects.Recorder = StaffLevel.ToString();
                    getidmasProjects.RecordDate = DateTime.Now;
                    getidmasProjects.Status = 1;
                }
                try
                {
                    db.SaveChanges();
                }
                catch (Exception ex)
                {

                }
            }

            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }
        public string ValidForNew(Models.Project_Filter Item, bool create = true) //create=true ให้เช็คค่าเลยกำหนดใน create กับ Edit ที่สร้างมา
        {
            int StaffLevel = HttpContext.Session["StaffLevel"] == null ? 0 : (int)HttpContext.Session["StaffLevel"];
            string resume = string.Empty;
            string ErrorAlert = string.Empty;
            string ErrorRow = string.Empty;
            //int n;

            if (Item != null)
            {
                if (create)
                {
                    if (Item.Name == null)
                    {
                        resume += "AA,";
                    }
                    else if (Item.Name.Count() >= 255)
                    {
                        resume += "AB,";
                    }

                }
                else
                {
                    if (Item.Name == null)
                    {
                        resume += "AA,";
                    }
                    else if (Item.Name.Count() >= 255)
                    {
                        resume += "AB,";
                    }
                }

                ErrorRow += ";";
            }

            resume += "/" + ErrorRow;
            resume += "/" + ErrorAlert;
            string resumetest = resume.Replace('/', ' ');
            resumetest = resumetest.Replace(';', ' ');
            if (resumetest.Trim() == string.Empty) { resume = string.Empty; }
            return resume;
        }
        public ActionResult Delete(int ID)
        {
            int StaffLevel = HttpContext.Session["StaffLevel"] == null ? 0 : (int)HttpContext.Session["StaffLevel"];
            var Item = db.masProjects.Find(ID);
            return PartialView(Item);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Models.Project_Filter Item)
        {
            int StaffLevel = HttpContext.Session["StaffLevel"] == null ? 0 : (int)HttpContext.Session["StaffLevel"];

            if (Item != null)
            {
                var getidmasProjects = db.masProjects.FirstOrDefault(s => s.ID == Item.ID);
                if (getidmasProjects != null)
                {
                    getidmasProjects.Recorder = StaffLevel.ToString();
                    getidmasProjects.RecordDate = DateTime.Now;
                    getidmasProjects.Status = 0;
                }
                try
                {
                    db.SaveChanges();
                }
                catch (Exception ex)
                {

                }
            }

            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }
        //    try
        //    {
        //        if (HttpContext.Session["Emp_ID"] == null)
        //        {
        //            return RedirectToAction("LogIn", "Home");
        //        }
        //        ServicePointManager.ServerCertificateValidationCallback = ((sender, certificate, chain, SslPolicyErrors) => true);
        //        ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12 | SecurityProtocolType.Ssl3;

        //        var clientsta = new RestClient(webAPIURL + "/api/pf_divisionApi?search={BRANCH_ID:'" + Branch_ID + "', DIVISION_ID:'" + Division_ID + "', PROFILE_ID:"+Profile_ID+"}&Full=true");
        //        var requeststa = new RestRequest(Method.GET);
        //        requeststa.AddHeader("postman-token", "0f6bdaf6-04ac-2bd1-28f1-bafb5ac05519");
        //        requeststa.AddHeader("cache-control", "no-cache");
        //        IRestResponse responsesta = clientsta.Execute(requeststa);
        //        List<Models.AlarmDivision> myAlarmDiv= new List<AlarmDivision>();
        //        if (responsesta.StatusCode.ToString() == "OK")
        //        {
        //            myAlarmDiv = Newtonsoft.Json.JsonConvert.DeserializeObject<List<Models.AlarmDivision>>(responsesta.Content);
        //        }

Task/Views/Project/Create.cshtml
@model Models.Project_Filter

@using (Html.BeginForm("Create", "Project", FormMethod.Post, new { id = "form0", enctype = "multipart/form-data" }))
{
    <div class="modal-dialog modal-lg" style="width: 800px; left: -150px">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">@Resources.Resource.Create</h4>
            </div>
            <div class="modal-body" style="width: 600px;">
                @Html.AntiForgeryToken()
                <div class="form-horizontal">
                    @Html.ValidationSummary(true)
                    <div class="form-group">
                        @Html.Label("Name", new { @class = "control-label col-md-5" })
                        <div class="col-md-7">
                            @Html.EditorFor(models => models.Name, new { @class = "control-label col-md-5", Styles = "width:100%" })
                            <span id="AError" class="ValidDateError"></span>
                        </div>
                    </div>
                </div>
            </div>
            @{ Html.RenderPartial("../Loading"); }

            <div class="modal-footer">
                <input type="button" class="btn" onclick="hideDialog();" value="@Resources.Resource.Close">
                <input type="submit" value="@Resources.Resource.Save" class="btn btn-primary btn-md" />
            </div>

        </div>
    </div>

                }
<script src="~/Scripts/CHO.js"></script>
<script lang="javascript">
    $(document).ready(function () {
        $(function () {
            var SubURL = '';
            $("#DueDate").datepicker({
                dateFormat: "dd/M/yy",
                changeMonth: true,
                changeYear: true,
                showButtonPanel: true,
                buttonImage: SubURL + "/images/calendar.gif",
                showOn: "both"
            });

        });



    });
</script>
<script type="text/javascript">


    $(function () {
        $("#form0").submit(function (event) {
            $("#inloading").show();
            var dataString;
            event.preventDefault();
            var action = $("#form0").attr("action");
            if ($("#form0").attr("enctype") == "multipart/form-data") {
                dataString = new FormData($("#form0").get(0));
                contentType = false;
                processData = false;
            } else {
                // regular form, do your own thing if you need it
            }
            $.ajax({
                type: "POST",
                url: action,
                data: dataString,
                //dataType: "json", //change to your own, else read my note above on enabling the JsonValueProviderFactory in MVC
                contentType: contentType,
                processData: processData,
                success: function (data) {
                    //BTW, data is one of the worst names you can make for a variable
                    //handleSuccessFunctionHERE(data);

                    alert("Add Data Success");
                    created();
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    $("#inloading").hide();
                    //$("#ErPosNo").html("test")
                    //alert(errorThrown);
                    errorClear();
                    Error(errorThrown);

                }
            });
        }); //end .submit()
    });

</script>

Task/Views/Project/Delete.cshtml
@model masProjects

@using (Html.BeginForm("Delete", "Project", FormMethod.Post, new { id = "form0", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="modal-dialog modal-lg" style="width:800px;left:-150px">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">@Resources.Resource.Delete</h4>
                <center><h4>@Html.Label("คุณต้องการลบ masProjects นี้ใช่หรือไม่")</h4></center>
            </div>
            <div class="modal-body" style="width:800px;">
                <div class="form-horizontal">
                    @Html.ValidationSummary(true)
                    @Html.HiddenFor(model => model.ID)
                    <div class="form-group">
                        @Html.Label("masProjects ID", new { @class = "control-label col-md-5" })
                        <div class="col-md-7">
                            @Html.DisplayFor(model => model.ID, new { @class = "control-label col-md-5", Styles = "width:100%" })
                            <span id="AError" class="ValidDateError"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.Label("Name", new { @class = "control-label col-md-5" })
                        <div class="col-md-7">
                            @Html.DisplayFor(model => model.Name, new { @class = "control-label col-md-5", Styles = "width:100%" })
                            <span id="CError" class="ValidDateError"></span>
                        </div>
                    </div>
                </div>
            </div>
            @{ Html.RenderPartial("../Loading"); }
            <div class="modal-footer">
                <input type="button" class="btn" onclick="hideDialog();" value="No">
                <input type="submit" value="Yes" class="btn btn-primary btn-md" />
            </div>
        </div>
    </div>
                }
<script src="~/Scripts/CHO.js"></script>
<script lang="javascript">
    $(document).ready(function () {
        $(function () {
            var SubURL = '';
            $("#DueDate").datepicker({
                dateFormat: "dd/M/yy",
                changeMonth: true,
                changeYear: true,
                showButtonPanel: true,
                buttonImage: SubURL + "/images/calendar.gif",
                showOn: "both"
            });

        });



    });
</script>
<script type="text/javascript">
    $(function () {
        $("#form0").submit(function (event) {
            $("#inloading").show(); var dataString;
            event.preventDefault();
            var action = $("#form0").attr("action");
            if ($("#form0").attr("enctype") == "multipart/form-data") {
                dataString = new FormData($("#form0").get(0));
                contentType = false;
                processData = false;
            } else {
                // regular form, do your own thing if you need it
            }
            $.ajax({
                type: "POST",
                url: action,
                data: dataString,
                //dataType: "json", //change to your own, else read my note above on enabling the JsonValueProviderFactory in MVC
                contentType: contentType,
                processData: processData,
                success: function (data) {
                    //BTW, data is one of the worst names you can make for a variable
                    //handleSuccessFunctionHERE(data);
                    $("#inloading").hide();
                    alert("Delete Data Success");
                    created();
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    $("#inloading").hide();
                    //$("#ErPosNo").html("test")
                    errorClear();
                    Error(errorThrown);

                }
            });
        }); //end .submit()
    });
</script>

Task/Views/Project/Edit.cshtml
@model Models.Project_Filter

    @using (Html.BeginForm("Edit", "Project", FormMethod.Post, new { id = "form0", enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        <div class="modal-dialog modal-lg" style="width:800px;left:-150px">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">@Resources.Resource.Edit</h4>
                </div>
                <div class="modal-body" style="width:800px;">
                    <div class="form-horizontal">
                        @Html.ValidationSummary(true)
                        @Html.HiddenFor(model => model.ID)
                        <div class="form-group">
                            @Html.Label("Task ID", new { @class = "control-label col-md-5" })
                            <div class="col-md-7">
                                @Html.DisplayFor(model => model.ID, new { @class = "control-label col-md-5", Styles = "width:100%" })

                            </div>
                        </div>
                        <div class="form-group">
                            @Html.Label("Name", new { @class = "control-label col-md-5" })
                            <div class="col-md-7">
                                @Html.EditorFor(model => model.Name, new { @class = "control-label col-md-5", Styles = "width:100%" })
                                <span id="AError" class="ValidDateError"></span>
                            </div>
                        </div>
                    </div>
                </div>
                @{ Html.RenderPartial("../Loading"); }
                <div class="modal-footer">
                    <input type="button" class="btn" onclick="hideDialog();" value="@Resources.Resource.Close">
                    <input type="submit" value="@Resources.Resource.Save" class="btn btn-primary btn-md" />
                </div>
            </div>
        </div>
                    }
    <script src="~/Scripts/CHO.js"></script>
    <script lang="javascript">
        $(document).ready(function () {
            $(function () {
                var SubURL = '';
                $("#DueDate").datepicker({
                    dateFormat: "dd/M/yy",
                    changeMonth: true,
                    changeYear: true,
                    showButtonPanel: true,
                    buttonImage: SubURL + "/images/calendar.gif",
                    showOn: "both"
                });

            });



        });
    </script>
    <script type="text/javascript">
        $(function () {
            $("#form0").submit(function (event) {
                $("#inloading").show(); var dataString;
                event.preventDefault();
                var action = $("#form0").attr("action");
                if ($("#form0").attr("enctype") == "multipart/form-data") {
                    dataString = new FormData($("#form0").get(0));
                    contentType = false;
                    processData = false;
                } else {
                    // regular form, do your own thing if you need it
                }
                $.ajax({
                    type: "POST",
                    url: action,
                    data: dataString,
                    //dataType: "json", //change to your own, else read my note above on enabling the JsonValueProviderFactory in MVC
                    contentType: contentType,
                    processData: processData,
                    success: function (data) {
                        //BTW, data is one of the worst names you can make for a variable
                        //handleSuccessFunctionHERE(data);
                        $("#inloading").hide();
                        alert("Edit Data Success");
                        created();
                    },
                    error: function (jqXHR, textStatus, errorThrown) {
                        $("#inloading").hide();
                        //$("#ErPosNo").html("test")
                        errorClear();
                        Error(errorThrown);

                    }
                });
            }); //end .submit()
        });
    </script>

Task/Views/Project/Index.cshtml
@model Models.Project_Filter
<div class="container">
    @using (@Ajax.BeginForm("List", "Project", null,
                new AjaxOptions()
                {
                    HttpMethod = "GET",
                    LoadingElementId = "inloading",
                    UpdateTargetId = "viewContent",
                    InsertionMode = InsertionMode.Replace,
                    OnFailure = "Failure( xhr, status, error)"

                },
                new
                {
                    id = "listingForm"
                    ,
                    enctype = "multipart/form-data"
                }

                ))
    {
        <div class="col-md-3">
            <div class="panel panel-default">
                <!-- Default panel contents -->
                <div class="panel-heading">
                    <button role="button" class="btn btn-primary" onclick="pageTo(1)">@Resources.Resource.Search</button>
                </div>
                <div class="panel-body">
                    <div class="form-group">
                        <input type="text" class="form-group from-control" id="ID" name="ID" placeholder="ID Search" style="width:100%" />
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-group from-control" id="Name" name="Name" placeholder="Name Search" style="width:100%" />
                    </div>
                    <input type="hidden" id="PageNo" name="PageNo" />
                </div>
            </div>
        </div>
    }
    <p></p>
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="modal-title" id="myModalLabel"></h4>
            </div>
            <div class="panel-body">
                @Html.ActionLink(@Resources.Resource.Add, "Create", null,
        new
        {
            @class = "btn btn-primary btn-md",
            data_toggle = "modal",
            data_target = "#detailsDialog",
            role = "button"
        })
                <div class="form-horizontal">
                    @Html.ValidationSummary(true)
                </div>
            </div>
            @{ Html.RenderPartial("../Loading"); }

            <div id="viewContent">
            </div>
        </div>
    </div>
    <div class="modal fade" id="detailsDialog" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    </div>
    <script>
        function MsgError(Code) {
            switch (Code) {
                case 'AA': return 'กรุณากรอกข้อมูล'; break;
                case 'AB': return 'ข้อมูลเกิน 255 ตัวอักษร กรุณากรอกข้อมูลใหม่'; break;
                    //case 'AC': return 'ห้ามมีค่าน้อยกว่า 0'; break;
                    //case 'BA': return 'กรุณากรอกข้อมูลแต่ห้ามเกิน 50 ตัวอักษร'; break;
                    //case 'BB': return 'ข้อมูลเกิน 50 ตัวอักษร กรุณากรอกข้อมูลใหม่'; break;
                    //case 'BC': return 'ห้ามมีค่าน้อยกว่า 0'; break;
                    //case 'CA': return 'กรุณากรอกข้อมูลแต่ห้ามเกิน 50 ตัวอักษร'; break;
                    //case 'CB': return 'ข้อมูลเกิน 50 ตัวอักษร กรุณากรอกข้อมูลใหม่'; break;
                    //case 'CC': return 'ห้ามมีค่าน้อยกว่า 0'; break;
                    //case 'DA': return 'ต้องเป็นจำนวนเต็มและห้ามมีค่าเกินกว่า 100,000'; break;
                    //case 'DB': return 'กรุณากรอกเฉพาะตัวเลขเท่านั้น'; break;
                    //case 'DC': return 'ห้ามมีค่าน้อยกว่า 0'; break;
                    //case 'EA': return 'ต้องเป็นจำนวนเต็มและห้ามมีค่าเกินกว่า 100,000'; break;
                    //case 'EB': return 'กรุณากรอกเฉพาะตัวเลขเท่านั้น'; break;
                    //case 'EC': return 'ห้ามมีค่าน้อยกว่า 0'; break;
                    //case 'FA': return 'ต้องเป็นจำนวนเต็มและห้ามมีค่าเกินกว่า 100,000'; break;
                    //case 'FB': return 'กรุณากรอกเฉพาะตัวเลขเท่านั้น'; break;
                    //case 'FC': return 'ห้ามมีค่าน้อยกว่า 0'; break;
                case 'ZZ': return 'Error'; break;
            }
        }

    </script>
    <script lang="javascript">
        $(document).ready(function () {
            // enable tooltip for <a>
            //$("a").tooltip();
            //$("#StatusID").css('width', "100%");
            //$("#StatusID").css('height', 35);
            //$("#StaffID").css('width', "100%");
            //$("#StaffID").css('height', 35);
            //$("#ProjectID").css('width', "100%");
            //$("#ProjectID").css('height', 35);
            // http://stackoverflow.com/questions/12286332/twitter-bootstrap-remote-modal-shows-same-content-everytime
            $('#detailsDialog').on('hidden.bs.modal', function () {
                $(this).removeData('bs.modal');
            });

            // config validation for dialog
            $('#detailsDialog').on('shown.bs.modal', function () {
                configDialog($(this));
            });

            // load page 1
            $('#listingForm').submit();
            $('#listingForm2').submit();
        });

        function configDialog($DialogContainer) {
            var $jQval = $.validator; //This is the validator
            $jQval.unobtrusive.parse($DialogContainer); // and here is where you set it up.
            $DialogContainer.modal();

            // setup validation
            var $form = $DialogContainer.find("form");
            $.validator.unobtrusive.parse($form);

            // validate before submmit
            $form.on("submit", function (event) {
                var $form = $(this);
                if (!$form.valid())
                    return false;
                event.preventDefault();
            });
        }

        function hideDialog() {
            $('#detailsDialog').modal('hide');
        }

        function created() {
            hideDialog();
            $('#listingForm').submit();
        }
        function Failure(xhr, status, error) {

            Error(error);
        }
        function Edited() {
            hideDialog();
            $('#listingForm').submit();
            //window.location.replace(Product);
        }

        function pageTo(pageNo) {
            $('#PageNo').val(pageNo);
            $('#listingForm').submit();
        }
    </script>
    <script src="~/Scripts/CHO.js"></script>
    <script type="text/javascript">
        $(function () {
            $("#form0").submit(function (event) {
                $("#inloading").show(); var dataString;
                event.preventDefault();
                var action = $("#form0").attr("action");
                if ($("#form0").attr("enctype") == "multipart/form-data") {
                    dataString = new FormData($("#form0").get(0));
                    contentType = false;
                    processData = false;
                } else {
                    // regular form, do your own thing if you need it
                }
                $.ajax({
                    type: "POST",
                    url: action,
                    data: dataString,
                    //dataType: "json", //change to your own, else read my note above on enabling the JsonValueProviderFactory in MVC
                    contentType: contentType,
                    processData: processData,
                    success: function (data) {
                        //BTW, data is one of the worst names you can make for a variable
                        //handleSuccessFunctionHERE(data);
                        created();
                    },
                    error: function (jqXHR, textStatus, errorThrown) {
                        alert("error");
                        $("#inloading").hide();
                        //$("#ErPosNo").html("test")
                        errorClear();
                        Error(errorThrown);

                    }
                });
            }); //end .submit()
        });
    </script>
    @*save all branch*@
    <script lang="javascript">
        $(function () {
            // this initializes the dialog (and uses some common options that I do)
            $("#dialog").dialog({
                autoOpen: false,
                modal: true,
                show: "blind",
                hide: "blind",
                appendTo: "#bottomOfForm",
                buttons: {
                    'Submit': function () {
                        //$j(this).parent().prependTo($j("#bottomOfForm"));
                        $(this).dialog('close');
                        submit = true;
                        $("#form0").submit();

                    }
                }
            });
        });
    </script>