Task/Models/TsTask.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Models
{
    public partial class tranTsTask
    {
        public tranTsTask()
        {
            FileComment = new List<FileCM>();
        }
        public int ProjectID { get; set; }
        public string ProjectName { get; set; }
        public int ID { get; set; }
        public string Name { get; set; }
        public string Remark { get; set; }
        public string DueDate { get; set; }
        public string StartDate { get; set; }
        public Nullable<int> StaffID { get; set; }
        public string StaffName { get; set; }
        public string Email { get; set; }
        public int StatusID { get; set; }
        public string StatusName { get; set; }
        public string PlatformName { get; set; }
        public int PlatformID { get; set; }
        public int imsg { get; set; }
        public int Approve { get; set; }
        //----------ชื่อผู้รับ ผู้ส่ง วันส่งทดสอบ----------//
        public int SenderID { get; set; }
        public string SenderName { get; set; }
        public int RecevierID { get; set; }
        public string RecevierIDName { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MMM/yyyy}")]
        public System.DateTime DateReccode { get; set; }
        //============ File & Comment =============
        public List<FileCM> FileComment { get; set; }
    }

    public class FileCM
    {
        public string OldFiles { get; set; }
        public HttpPostedFileBase FilesData { get; set; }
        public string Comment { get; set; }
        public bool ReviewFile { get; set; }
        public int IDmapTask { get; set; }
    }

    public class TsTask_Filter
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Remark { get; set; }
        public int ProjectID { get; set; }
        public string ProjectName { get; set; }
        public int StaffID { get; set; }
        public string StaffName { get; set; }
        public int StatusID { get; set; }
        public string StatusName { get; set; }
        public string PlatformName { get; set; }
        public int PlatformID { get; set; }
        public int? RecorderID { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MMM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> DueDate { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MMM/yyyy}")]
        public Nullable<System.DateTime> StartDate { get; set; }
        public DateTime? FilterDueDate { get; set; }
        public bool UnShowFinish { get; set; }
        public bool UnShowCancel { get; set; }
        public int Approve { get; set; }
    }
    public partial class tranTsTasksh
    {
        public int ProjectID { get; set; }
        public string ProjectName { get; set; }
        public int ID { get; set; }
        public string Name { get; set; }
        public string Remark { get; set; }
        public string DueDate { get; set; }
        public string StartDate { get; set; }
        public string StaffID { get; set; }
        public string StaffName { get; set; }
        public int StatusID { get; set; }
        public string StatusName { get; set; }
        public int PlatformID { get; set; }
        public string PlatformName { get; set; }
        public int Approve { get; set; }
        public List<FileCM> FileComment { get; set; }
        //----------ชื่อผู้รับ ผู้ส่ง วันส่งทดสอบ----------//
        public int SenderID { get; set; }
        public int RecevierID { get; set; }
        public System.DateTime DateReccode { get; set; }
        //--------------------------------------//
    }
}

Task/Controllers/TsTaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using RestSharp;
using Models;
using System.Web.Script.Serialization;
using System.Net;
using System.Reflection;
using PagedList;
using System.IO;
using Repo;
using static Repo.sendEmail;

namespace Task.Controllers
{
    public class TsTaskController : Controller
    {
        // GET: TsTask
        private int pageSize = 10;
        public ActionResult Index()
        {
            JobsEntities db = new JobsEntities();
            int StaffLevel = HttpContext.Session["StaffLevel"] == null ? 0 : (int)HttpContext.Session["StaffLevel"];
            if (StaffLevel <= 0)
            {
                return RedirectToAction("LogIn", "Home");
            }
            ViewBag.StaffLevel = StaffLevel;
            var aa = db.masStaffs.Where(w => w.Status > 0 && w.StaffLevel == 3).ToList();

            if (aa.Count() > 0)
            {
                var rs = aa.ToList();
                List<dropdownAuto> dataDropdown = new List<dropdownAuto>();
                foreach (var s in rs)
                {
                    dataDropdown.Add(new dropdownAuto()
                    {
                        ID = s.ID,
                        Name = s.Name,
                        Email = s.Email ?? ""
                    });
                }
                ViewBag.StaffID = dataDropdown;
            }
            else
            {
                ViewBag.StaffID = new Models.dropdownAuto();
            }
            var bb = db.masTaskStatus.Where(w => w.Status > 0).ToList();
            if (bb.Count() > 0)
            {
                ViewBag.StatusID = bb.Select(s => new Models.dropdownAuto { ID = s.ID, Name = s.Name }).ToList();
            }
            else
            {
                ViewBag.StatusID = new Models.dropdownAuto();
            }
            var cc = db.masProjects.Where(w => w.Status > 0).ToList();
            if (cc.Count() > 0)
            {
                ViewBag.ProjectID = cc.Select(s => new Models.dropdownAuto { ID = s.ID, Name = s.Name }).ToList(); 
            }
            else
            {
                ViewBag.ProjectID = new Models.dropdownAuto(); 
            }

            ViewBag.TaskId = "-1";

            return View();
        }
        public ActionResult List(Models.Task_Filter Filter, int pageNO = 1)
        {
            JobsEntities db = new JobsEntities();
            int StaffLevel = HttpContext.Session["StaffLevel"] == null ? 0 : (int)HttpContext.Session["StaffLevel"];
            ViewBag.StaffLevel = StaffLevel;
            string IDStaff = "";
            int IDStaff_num = 0;
            if (HttpContext.Session["LoginID"] != null)
            {
                IDStaff = HttpContext.Session["IDStaff"].ToString();

                IDStaff_num = int.Parse(IDStaff);
                ViewBag.IDStaff = IDStaff_num;
            }
            else
            {
                return RedirectToAction("LogIn", "Home");
            }

            try
            {
                var Task = db.tranTasks.AsQueryable();
               
                if (Filter != null)
                {
                    if (Filter.UnShowFinish)
                    {
                        Task = Task.Where(w => w.StatusID != 2);
                    }
                    if (Filter.UnShowCancel)
                    {
                        Task = Task.Where(w => w.StatusID != 0);
                    }
                    if (Filter.StaffID > 0)
                    {
                        Task = Task.SelectMany(sm => sm.tranHistory.Where(w => w.Receiver == Filter.StaffID)).Select(s => s.tranTasks).AsQueryable();
                        //if (!String.IsNullOrEmpty(Filter.StaffName))
                        //{
                        //    //Task = Task.Where(w => w.masStaffs.Name.Contains(Filter.StaffName)).AsQueryable();
                        //    var TaskHis = db.tranHistory.AsQueryable();
                        //    TaskHis = TaskHis.Where(w => w.Receiver == Filter.StaffID).AsQueryable();
                        //}
                        //else
                        //{
                        //    Task = Task.Where(w => w.StaffID == Filter.StaffID).AsQueryable();
                        //}
                        //Task = Task.Where(w => w.StaffID == Filter.StaffID).AsQueryable();
                    }
                    if (Filter.StatusID > 0 || !String.IsNullOrEmpty(Filter.StatusName))
                    {
                        if (!String.IsNullOrEmpty(Filter.StatusName))
                        {
                            Task = Task.Where(w => w.masTaskStatus.Name.Contains(Filter.StatusName)).AsQueryable();
                        }
                        else
                        {
                            Task = Task.Where(w => w.StatusID == Filter.StatusID).AsQueryable();
                        }
                    }
                    if (Filter.StatusID > 0 || !String.IsNullOrEmpty(Filter.PlatformName))
                    {
                        if (!String.IsNullOrEmpty(Filter.PlatformName))
                        {
                            Task = Task.Where(w => w.masTaskStatus.Name.Contains(Filter.PlatformName)).AsQueryable();
                        }
                        else
                        {
                            Task = Task.Where(w => w.StatusID == Filter.StatusID).AsQueryable();
                        }
                    }
                    if (Filter.ProjectID > 0 || !String.IsNullOrEmpty(Filter.ProjectName))
                    {
                        if (!String.IsNullOrEmpty(Filter.ProjectName))
                        {
                            Task = Task.Where(w => w.masProjects.Name.Contains(Filter.ProjectName)).AsQueryable();
                        }
                        else
                        {
                            Task = Task.Where(w => w.ProjectID == Filter.ProjectID).AsQueryable();
                        }
                        //Task = Task.Where(w => w.ProjectID == Filter.ProjectID).AsQueryable();
                    }
                }



                if (Filter.FilterDueDate != null)
                {
                    //DateTime DueDateBegin = Filter.FilterDueDate.Value.Date;
                    DateTime DueDateEnd = Filter.FilterDueDate.Value.AddDays(1).Date.AddMinutes(-1);
                    Task = Task.Where(w => w.DueDate <= DueDateEnd).AsQueryable();
                }

                Task = Task.Where(w => w.StatusID == 4 || (w.Approve == 2 && w.StatusID == 1)).AsQueryable();

                List<Models.tranTsTask> MTask = new List<Models.tranTsTask>();
                MTask = Task.Select(EntityToModel).ToList();
                var Result = MTask.OrderBy(s => s.DateReccode).GroupBy(g => g.ID).Select(a => new Models.tranTsTask
                {
                    ID = a.Key,
                    Approve = a.Select(s => s.Approve).FirstOrDefault(),
                    ProjectID = a.Select(s => s.ProjectID).FirstOrDefault(),
                    ProjectName = a.Select(s => s.ProjectName).FirstOrDefault(),
                    Name = a.Select(s => s.Name).FirstOrDefault(),
                    DateReccode = a.Select(s => s.DateReccode).Max(),
                    RecevierID = a.Select(s => s.RecevierID).FirstOrDefault(),
                    RecevierIDName = a.Select(s => s.RecevierIDName).FirstOrDefault(),
                    PlatformID = a.Select(s => s.PlatformID).FirstOrDefault(),
                    PlatformName = a.Select(s => s.PlatformName).FirstOrDefault(),
                    StatusID = a.Select(s => s.StatusID).FirstOrDefault(),
                    StatusName = a.Select(s => s.StatusName).FirstOrDefault(),
                    StaffID = a.Select(s => s.StaffID).FirstOrDefault(),
                    StaffName = a.Select(s => s.StaffName).FirstOrDefault(),
                }).ToList();
                int.TryParse(Properties.Settings.Default.pageSize.ToString(), out pageSize);
                if (pageSize <= 0) { pageSize = 10; }
                int pageIdx = pageNO - 1;
                int totalItemCount = Task.Count();
                var paged = Result.OrderBy(o => o.DueDate).Skip(pageIdx * pageSize).Take(pageSize);
                var pageresult = new StaticPagedList<Models.tranTsTask>(paged, pageNO, pageSize, totalItemCount);
                return PartialView(pageresult);
            }
            catch (Exception ex)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, ex.ToString());
            }
        }
       
        private Models.tranTsTask EntityToModel(tranTasks Value)
        {
            int StaffLevel = HttpContext.Session["StaffLevel"] == null ? 0 : (int)HttpContext.Session["StaffLevel"];
            var mapTaskDetail = Value.mapTaskTsDetail.Select(s => new { ID = s.ID, Comment = s.Comment }).ToList();
            var TaskDetailList = mapTaskDetail.Select(s => new Models.FileName { Index = s.ID.ToString(), Comment = s.Comment }).ToList();
           
            return new Models.tranTsTask()
            {
                ID = Value.ID,
                Name = Value.Name, 
                ProjectID = Value.ProjectID,
                ProjectName = Value.masProjects.Name,
                Remark = Value.Remark,
                StaffID = Value.StaffID == null ? -1 : Value.StaffID,
                StaffName = Value.masStaffs == null ? "" : Value.masStaffs.Name,      
                StatusID = Value.StatusID,
                StatusName = Value.masTaskStatus.Name,
                PlatformID = Value.PlatformID == null ? -1 : (int)Value.PlatformID,
                PlatformName = Value.masPlatform.Name,
                DateReccode = Value.tranHistory.OrderByDescending(w => w.DateRecode).FirstOrDefault().DateRecode,

Task/Views/TsTask/Detail.cshtml
@model Models.tranTsTasksh

@*@{
        ViewBag.Title = "Detail";
    }*@

<style>
    .scrollbars1 {
        width: 100%;
        max-height: 150px;
        margin-top: 20px;
        overflow: hidden scroll; /* showing scrollbars */
    }

    .scrollbars2 {
        width: 100%;
        height: 150px;
        margin-top: 20px;
        overflow: hidden hidden; /* showing scrollbars */
    }
</style>
@Html.AntiForgeryToken()
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title" id="myModalLabel">Detail</h4>
        </div>
        <div class="modal-body">
            <div>

                <dl class="dl-horizontal">
                    <dt>
                        ID :
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.ID)
                    </dd>
                    <dt>
                        โปรเจค :
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.ProjectName)
                    </dd>
                    <dt>
                        Task :
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Name)
                    </dd>
                    <dt>
                        กำหนดส่ง :
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.DueDate)
                    </dd>
                    <dt>
                        Remark :
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Remark)
                    </dd>
                    <dt>
                        ผู้รับผิดชอบ :
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.StaffName)
                    </dd>
                    <dt>
                        สถานะ :
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.StatusName)
                    </dd>
                    <dt>
                        รูปแบบ :
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.PlatformName)
                    </dd>
                    <dt>
                        @*@if (Model.Approve > 0)
                        {*@
                            <label>
                                ผลการตรวจสอบ:
                            </label>
                        @*}
                        else
                        {

                        }*@
                    </dt>
                    <dd>
                        @*@if (Model.Approve > 0)
                        {*@
                            @Html.DisplayFor(model => model.Approve)
                        @*}
                        else
                        {

                        }*@
                    </dd>

                    <dt style="margin-top: 10px;">
                        @if (Model.FileComment.Count > 0)
                        {
                            <label>
                                รูป/ความคิดเห็น :
                            </label>
                        }
                        else
                        {

                        }
                    </dt>
                    <dd>
                        @if (Model.FileComment.Count > 0)
                        {
                            <div class="scrollbars1">
                                @foreach (var File in Model.FileComment)
                                {

                                    <div class="overflow-auto">
                                        <a target="_blank" href="@File.FilesData" @if (!File.ReviewFile) { @Html.Raw("download") }>
                                            @File.OldFiles
                                        </a>
                                        <br />
                                    </div>
                                }
                                @foreach (var commentItem in Model.FileComment)
                                {
                                    <div class="overflow-auto">
                                        <textarea type="text" style="width:100%;float:left;margin-right:unset;">
                                            @commentItem.Comment
                                        </textarea>
                                    </div>
                                }
                            </div>

                        }
                        else
                        {

                        }

                    </dd>

                </dl>
            </div>
        </div>

        @{ Html.RenderPartial("../Loading"); }
        <div class="modal-footer">
            <input type="button" class="btn" onclick="hideDialog();" value="@Resources.Resource.Close">
        </div>
    </div>
</div>

Task/Views/TsTask/DetailRow.cshtml
@model Models.FileCM
@{ ViewData.TemplateInfo.HtmlFieldPrefix = ViewBag.HtmlFieldPrefix; }

<tr>

    <input type="hidden" name="FileComment.Index" id="FileComment.Index" value="@ViewBag.Index" />
    <td style="width:20%"></td>
    <td valign="top" style="width:10%">
        <input type="file" id="filedata" style="width:80px;float:left;margin-right:unset;" name="FileComment[@ViewBag.Index].FilesData" value="@ViewBag.Index" onchange="filedatachangename(this,'@ViewBag.Index')" />
    </td>
    <td style="padding-bottom:30px;width:30%;">
        <label class="custom-file-label position" for="FileComment_@ViewBag.Index">Chooes file</label>
        <br/>
        <textarea  id="Comment_@ViewBag.Index" style="width:100%;float:left;margin-right:unset;" name="FileComment[@ViewBag.Index].Comment" />
    </td>
    <td valign="top" style="width:30%;padding-left:20px;">
        <button class="btn btn-danger btn-md" onclick="Delete(this,'@ViewBag.Index')">Delete</button>
        <span id="GError" class="ValidDateError" style="text-align:left"></span>
    </td>
</tr>

Task/Views/TsTask/List.cshtml
@model PagedList.IPagedList<Models.tranTsTask>
<style>
    .Name {
        text-align: left;
    }
</style>
<table class="table">
    <thead>
        <tr style="background-color:red; color:white">
            <th class="Name">@Html.Label("Task ID")</th>
            <th class="Name">@Html.Label("Project")</th>
            <th class="Name">@Html.Label("Task")</th>
            <th class="Name">@Html.Label("วันส่งทดสอบ")</th>
            <th class="Name">@Html.Label("Responsible")</th>
            <th class="Name">@Html.Label("OS")</th>
            <th class="Name">@Html.Label("Status")</th>
            <th class="Name">@Html.Label("Approve")</th>
            <th style="text-align:right;padding-right:1.5em"><span class="badge">@Model.TotalItemCount</span>  @Resources.Resource.Records</th>
        </tr>
    </thead>
    <tbody>

        @foreach (Models.tranTsTask Item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => Item.ID)
                </td>
                <td class="Name">
                    @Html.HiddenFor(model => Item.ID)
                    @Html.DisplayFor(modelItem => Item.ProjectName)
                </td>
                <td class="Name">
                    @Html.DisplayFor(modelItem => Item.Name)
                </td>
                <td>
                    @*@Html.DisplayFor(modelItem => Item.DueDate, new { @Value = Convert.ToString(Item.DueDate.ToString("dd-MMM-yy")) })*@
                    @Html.DisplayFor(modelItem => Item.DateReccode)
                </td>
                <td>
                    @if (Item.Approve == 2 && Item.StatusID == 1)
                    {
                        @Html.DisplayFor(modelItem => Item.StaffName)
                    }
                    else
                    {
                        @Html.DisplayFor(modelItem => Item.RecevierIDName)
                    }

                </td>
                <td>
                    @Html.DisplayFor(modelItem => Item.PlatformName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => Item.StatusName)
                </td>
                <td>
                    @if (Item.Approve == 0)
                    {
                        @Html.Label("รอตรวจ")
                    }
                    else if (Item.Approve == 1)
                    {
                        @Html.Label("ผ่าน")
                    }
                    else if (Item.Approve == 2)
                    {
                        @Html.Label("ไม่ผ่าน")
                    }
                </td>
                <td style="text-align:right;">
                    @if (ViewBag.StaffLevel >= 1)
                    {
                        @Html.ActionLink(@Resources.Resource.Edit, "Edit", "TsTask", new { TsTaskID = Item.ID },
                    new
                    {
                        @class = "btn btn-danger btn-md",
                        data_toggle = "modal",
                        data_target = "#TsEditsDialog",
                        role = "button"
                    });
                    }
                    @if (ViewBag.StaffLevel >= 1)
                    {
                        @Html.ActionLink(@"Detail", "Detail", "TsTask", new { TsTaskID = Item.ID },
                    new
                    {
                        @class = "btn btn-primary btn-md",
                        data_toggle = "modal",
                        data_target = "#TsEditsDialog",
                        role = "button"
                    });
                    }

                </td>
            </tr>
        }


    </tbody>
</table>
<div class="panel-footer" style="height:100px;">
    <div style="z-index:1;position: absolute;">
        @Html.PagedListPager(Model, page => "javascript:pageNewTo(" + page + ");")
    </div>
</div>

Task/Views/TsTask/ListNew.cshtml
@model PagedList.IPagedList<Models.tranTsTask>
<style>
    .Name {
        text-align: left;
    }
</style>
<table class="table">
    <thead>
        <tr style="background-color:red; color:white">
            <th class="Name">@Html.Label("Task ID")</th>
            <th class="Name">@Html.Label("Project")</th>
            <th class="Name">@Html.Label("Task")</th>
            <th class="Name">@Html.Label("วันส่งทดสอบ")</th>
            <th class="Name">@Html.Label("Responsible")</th>
            <th class="Name">@Html.Label("OS")</th>
            <th class="Name">@Html.Label("Status")</th>
            <th class="Name">@Html.Label("Approve")</th>
            <th style="text-align:right;padding-right:1.5em"><span class="badge">@Model.TotalItemCount</span>  @Resources.Resource.Records</th>
        </tr>
    </thead>
    <tbody>

        @foreach (Models.tranTsTask Item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => Item.ID)
                </td>
                <td class="Name">
                    @Html.HiddenFor(model => Item.ID)
                    @Html.DisplayFor(modelItem => Item.ProjectName)
                </td>
                <td class="Name">
                    @Html.DisplayFor(modelItem => Item.Name)
                </td>
                <td>
                    @*@Html.DisplayFor(modelItem => Item.DueDate, new { @Value = Convert.ToString(Item.DueDate.ToString("dd-MMM-yy")) })*@
                    @Html.DisplayFor(modelItem => Item.DateReccode)
                </td>
                <td>
                    @if (Item.Approve == 2 && Item.StatusID == 1)
                    {
                        @Html.DisplayFor(modelItem => Item.StaffName)
                    }
                    else
                    {
                        @Html.DisplayFor(modelItem => Item.RecevierIDName)
                    }

                </td>
                <td>
                    @Html.DisplayFor(modelItem => Item.PlatformName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => Item.StatusName)
                </td>
                <td>
                    @if (Item.Approve == 0)
                    {
                        @Html.Label("รอตรวจ")
                    }
                    else if (Item.Approve == 1)
                    {
                        @Html.Label("ผ่าน")
                    }
                    else if (Item.Approve == 2)
                    {
                        @Html.Label("ไม่ผ่าน")
                    }
                </td>
                <td style="text-align:right;">
                    @if (ViewBag.StaffLevel >= 1)
                    {
                        @Html.ActionLink(@Resources.Resource.Edit, "Edit", "TsTask", new { TsTaskID = Item.ID },
                    new
                    {
                        @class = "btn btn-danger btn-md",
                        data_toggle = "modal",
                        data_target = "#TsEditsDialog",
                        role = "button"
                    });
                    }
                    @if (ViewBag.StaffLevel >= 1)
                    {
                        @Html.ActionLink(@"Detail", "Detail", "TsTask", new { TsTaskID = Item.ID },
                    new
                    {
                        @class = "btn btn-primary btn-md",
                        data_toggle = "modal",
                        data_target = "#TsEditsDialog",
                        role = "button"
                    });
                    }

                </td>
            </tr>
        }


    </tbody>
</table>
<div class="panel-footer">
    @Html.PagedListPager(Model, page => "javascript:pageNewTo(" + page + ");")
</div>